# Generated by Django 6.0 on 2025-12-10 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('gestor', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('Linguagem', 'Linguagem'), ('Framework', 'Framework'), ('Servico Cloud', 'Serviço Cloud'), ('Banco de Dados', 'Banco de Dados'), ('Outro', 'Outro')], max_length=50)),
                ('versao', models.CharField(blank=True, max_length=50, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Planejado', 'Planejado'), ('Em Execução', 'Em Execução'), ('Concluido', 'Concluído'), ('Cancelado', 'Cancelado')], default='Planejado', max_length=50)),
                ('risco', models.CharField(choices=[('Baixo', 'Baixo'), ('Medio', 'Médio'), ('Alto', 'Alto'), ('Critico', 'Crítico')], default='Baixo', max_length=50, verbose_name='Nível de Risco')),
                ('orcamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Orçamento (R$)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='portfolio.departamento')),
                ('tecnologias', models.ManyToManyField(related_name='projetos', to='portfolio.tecnologia')),
            ],
        ),
    ]
